import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Layout } from "@/components/layout/Layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { PayslipsManagement } from "@/components/payslips/PayslipsManagement";
import { formatBRL } from "@/lib/utils";
import { Search, Users, Palmtree, Clock3, FileText, Calculator, AlertTriangle, ShieldCheck } from "lucide-react";
import { format } from "date-fns";
import { ptBR } from "date-fns/locale";

const money = (v: unknown) => formatBRL(Number(v) || 0);
const dateBR = (v?: string | null) => v ? format(new Date(`${v.slice(0,10)}T12:00:00`), "dd/MM/yyyy", { locale: ptBR }) : "—";
const initials = (name = "") => name.split(" ").filter(Boolean).map(p => p[0]).slice(0,2).join("").toUpperCase();

export default function ContabilidadeDashboard() {
  const [search, setSearch] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const { data: employees = [], isLoading } = useQuery({
    queryKey: ["accounting-central-employees"],
    queryFn: async () => {
      const { data, error } = await supabase.from("user_profiles").select("id,full_name,email,avatar_url,cargo,departamento,salario,admission_date,employment_status").eq("tipo","colaborador").order("full_name");
      if (error) throw error;
      return data || [];
    }
  });
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return !q ? employees : employees.filter((e:any) => [e.full_name,e.email,e.cargo,e.departamento].join(" ").toLowerCase().includes(q)); }, [employees, search]);
  const selected = employees.find((e:any) => e.id === selectedId);

  return <Layout><div className="mx-auto w-full max-w-[1600px] space-y-6 px-4 pb-10 sm:px-6 lg:px-8">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary"><ShieldCheck className="h-3.5 w-3.5"/> CENTRAL DE CONTABILIDADE</div><h1 className="text-3xl font-bold tracking-tight">Prontuário trabalhista</h1><p className="mt-1 text-sm text-muted-foreground">A Contabilidade apura e informa direitos, ponto, férias e valores. O Financeiro é quem registra os pagamentos.</p></div><div className="relative w-full lg:w-96"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar colaborador..." className="h-11 rounded-xl pl-9"/></div></header>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Kpi icon={Users} label="Colaboradores" value={employees.length}/><Kpi icon={Palmtree} label="Férias" value="Direitos" caption="gozadas, agendadas e vencidas"/><Kpi icon={Clock3} label="Ponto" value="Apuração" caption="horas, faltas e atestados"/><Kpi icon={FileText} label="Holerites" value="Mensal" caption="documento + valores apurados"/></div>
    {isLoading ? <Card><CardContent className="py-16 text-center text-muted-foreground">Carregando colaboradores...</CardContent></Card> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map((employee:any)=><button key={employee.id} onClick={()=>setSelectedId(employee.id)} className="text-left"><Card className="h-full rounded-2xl border-border/70 transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-lg"><CardContent className="p-5"><div className="flex items-center gap-3"><Avatar className="h-14 w-14 border-2 border-primary/15"><AvatarImage src={employee.avatar_url || undefined}/><AvatarFallback>{initials(employee.full_name)}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate font-semibold">{employee.full_name}</p><p className="truncate text-xs text-muted-foreground">{employee.cargo || employee.departamento || "Colaborador"}</p><Badge variant="outline" className="mt-2">{employee.employment_status || "ativo"}</Badge></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-muted/40 p-2"><span className="text-muted-foreground">Salário-base</span><p className="font-semibold">{money(employee.salario)}</p></div><div className="rounded-xl bg-muted/40 p-2"><span className="text-muted-foreground">Admissão</span><p className="font-semibold">{dateBR(employee.admission_date)}</p></div></div><p className="mt-4 text-center text-xs font-semibold text-primary">Abrir prontuário</p></CardContent></Card></button>)}</div>}
    {selected && <EmployeeProfile employee={selected} onClose={()=>setSelectedId(null)}/>} 
  </div></Layout>;
}
function Kpi({icon:Icon,label,value,caption}:{icon:any,label:string,value:string|number,caption?:string}){return <Card className="rounded-2xl"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p>{caption&&<p className="mt-1 text-xs text-muted-foreground">{caption}</p>}</div><div className="rounded-xl bg-primary/10 p-3 text-primary"><Icon className="h-5 w-5"/></div></div></CardContent></Card>}
function EmployeeProfile({employee,onClose}:{employee:any,onClose:()=>void}){
 const {data:vacations=[]}=useQuery({queryKey:["accounting-profile-vacations",employee.id],queryFn:async()=>{const {data,error}=await supabase.from("vacation_requests").select("*").eq("user_id",employee.id).order("start_date",{ascending:false});if(error)throw error;return data||[];}});
 const {data:balances=[]}=useQuery({queryKey:["accounting-profile-balances",employee.id],queryFn:async()=>{const {data,error}=await supabase.from("vacation_balances").select("*").eq("user_id",employee.id).order("year",{ascending:false});if(error)throw error;return data||[];}});
 const {data:payments=[]}=useQuery({queryKey:["accounting-profile-salaries",employee.id],queryFn:async()=>{const {data,error}=await supabase.from("historico_pagamentos_funcionarios").select("*").eq("id_usuario",employee.id).order("ano_referencia",{ascending:false}).order("mes_referencia",{ascending:false}).limit(60);if(error)throw error;return data||[];}});
 const used=balances.reduce((s:number,b:any)=>s+Number(b.days_used||0),0); const available=balances.length?Number(balances[0].days_available||0):0;
 return <Card className="rounded-3xl border-primary/20 shadow-xl"><CardHeader className="flex flex-row items-center justify-between gap-4"><div className="flex items-center gap-4"><Avatar className="h-16 w-16"><AvatarImage src={employee.avatar_url||undefined}/><AvatarFallback>{initials(employee.full_name)}</AvatarFallback></Avatar><div><CardTitle>{employee.full_name}</CardTitle><p className="text-sm text-muted-foreground">{employee.cargo||employee.departamento||"Colaborador"} · admissão {dateBR(employee.admission_date)}</p></div></div><Button variant="outline" onClick={onClose}>Fechar</Button></CardHeader><CardContent><Tabs defaultValue="resumo" className="space-y-4"><TabsList className="w-full justify-start overflow-x-auto rounded-xl"><TabsTrigger value="resumo">Resumo</TabsTrigger><TabsTrigger value="ferias">Férias</TabsTrigger><TabsTrigger value="salarios">Salários</TabsTrigger><TabsTrigger value="ponto">Ponto</TabsTrigger><TabsTrigger value="holerites">Holerites</TabsTrigger><TabsTrigger value="13">13º</TabsTrigger></TabsList>
 <TabsContent value="resumo" className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><Metric title="Salário-base" value={money(employee.salario)}/><Metric title="Férias gozadas" value={`${used} dias`}/><Metric title="Disponível" value={`${available} dias`}/></div><Card className="rounded-2xl"><CardContent className="p-5"><p className="font-semibold">Regra de responsabilidade</p><p className="mt-2 text-sm text-muted-foreground">A Contabilidade informa direitos, apura ponto e anexa holerites. Esta área não registra pagamentos; o pagamento é responsabilidade do Financeiro.</p></CardContent></Card></TabsContent>
 <TabsContent value="ferias" className="space-y-3"><div className="grid gap-3 md:grid-cols-3">{balances.map((b:any)=><Card key={b.id} className="rounded-2xl"><CardContent className="p-4"><p className="font-semibold">{b.year}</p><p className="text-sm">{b.days_used||0} gozados · {b.days_available||0} disponíveis</p></CardContent></Card>)}</div>{vacations.map((v:any)=><Card key={v.id} className="rounded-2xl"><CardContent className="flex flex-col gap-2 p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{dateBR(v.start_date)} → {dateBR(v.end_date)}</p><p className="text-xs text-muted-foreground">{v.days} dias</p></div><Badge variant="outline">{v.status}</Badge></CardContent></Card>)}{!vacations.length&&<Empty text="Nenhuma férias registrada."/>}</TabsContent>
 <TabsContent value="salarios" className="space-y-3"><div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 text-sm"><AlertTriangle className="mr-2 inline h-4 w-4 text-amber-500"/> Valores abaixo são apurados/informados pela Contabilidade. O pagamento é registrado somente no módulo Salários do Financeiro.</div>{payments.map((p:any)=><Card key={p.id} className="rounded-2xl"><CardContent className="flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{String(p.mes_referencia||"").padStart(2,"0")}/{p.ano_referencia}</p><p className="text-xs text-muted-foreground">Bruto {money(p.salario_bruto||p.salario_holerite)}</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Líquido apurado</p><p className="font-bold">{money(p.salario_liquido||p.valor_total)}</p></div></CardContent></Card>)}{!payments.length&&<Empty text="Nenhuma competência registrada."/>}</TabsContent>
 <TabsContent value="ponto"><Card className="rounded-2xl"><CardContent className="p-5"><p className="font-semibold">Registro de ponto</p><p className="mt-1 text-sm text-muted-foreground">Consulte aqui as horas, faltas, justificativas e atestados utilizados na apuração mensal.</p><Button className="mt-4" variant="outline" disabled>Integração de ponto</Button></CardContent></Card></TabsContent>
 <TabsContent value="holerites"><PayslipsManagement employeeId={employee.id} employeeName={employee.full_name}/></TabsContent>
 <TabsContent value="13"><ThirteenthCalculator salary={Number(employee.salario||0)}/></TabsContent></Tabs></CardContent></Card>;
}
function Metric({title,value}:{title:string,value:string}){return <Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p></CardContent></Card>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div>}
function ThirteenthCalculator({salary}:{salary:number}){const [months,setMonths]=useState(12);const gross=salary/12*months;return <Card className="rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2"><Calculator className="h-5 w-5 text-primary"/> Calculadora de 13º</CardTitle></CardHeader><CardContent className="space-y-4"><div><label className="text-sm font-medium">Avos trabalhados</label><Input type="number" min={0} max={12} value={months} onChange={e=>setMonths(Number(e.target.value))}/></div><div className="grid gap-3 md:grid-cols-3"><Metric title="Bruto estimado" value={money(gross)}/><Metric title="1ª parcela" value={money(gross/2)}/><Metric title="2ª parcela" value={money(gross/2)}/></div><p className="text-xs text-muted-foreground">Estimativa. INSS/IRRF devem ser conferidos conforme a competência.</p></CardContent></Card>}
