import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, CalendarDays, ChevronRight, Radio, Users } from "lucide-react";
import { toast } from "sonner";
import { Layout } from "@/components/layout/Layout";
import { useAuth } from "@/contexts/AuthContext";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { listarReunioesTreinamento, type TrainingMeeting } from "@/components/centro-treinamento/trainingService";

export default function SalaReuniao() {
  const { roles } = useAuth();
  const [meetings, setMeetings] = useState<TrainingMeeting[]>([]);
  const [loading, setLoading] = useState(true);
  const canCreate = roles.includes("admin") || roles.includes("gestor_master");
  useEffect(() => { void listarReunioesTreinamento().then(setMeetings).catch((error) => toast.error(error instanceof Error ? error.message : "Não foi possível carregar as salas.")).finally(() => setLoading(false)); }, []);
  return <Layout><div className="mx-auto max-w-6xl space-y-7 px-4 py-6"><Link to="/centro-treinamento" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Voltar ao Centro Treinamento</Link><section className="rounded-3xl border border-slate-700 bg-[#152647] px-6 py-8 text-white shadow-xl sm:px-10"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-2xl"><div className="mb-4 flex items-center gap-2"><span className="flex size-10 items-center justify-center rounded-xl bg-amber-300/15 text-amber-200"><Radio className="size-5" /></span><Badge className="border-emerald-300/25 bg-emerald-300/10 text-emerald-100">Sala colaborativa</Badge></div><h1 className="text-3xl font-semibold tracking-tight">Sala de reunião</h1><p className="mt-3 text-sm leading-6 text-slate-300">Entre por vídeo, desligue sua câmera quando quiser e acompanhe a tela e a lousa compartilhadas pelo host.</p></div><div className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-200"><Users className="size-4 text-amber-200" /> Admin e gestor master criam salas</div></div></section><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Salas disponíveis</p><h2 className="mt-1 text-xl font-semibold">Reuniões da equipe</h2></div>{canCreate && <Link to="/centro-treinamento"><Button variant="outline">Criar na central</Button></Link>}</div>{loading ? <Card><CardContent className="py-12 text-center text-sm text-muted-foreground">Carregando salas…</CardContent></Card> : meetings.length === 0 ? <Card><CardContent className="py-12 text-center"><Radio className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">Nenhuma sala foi criada ainda.</p></CardContent></Card> : <div className="grid gap-3">{meetings.map((meeting) => <Card key={meeting.id} className="border-slate-200"><CardContent className="flex flex-wrap items-center justify-between gap-4 py-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold">{meeting.titulo}</h3><Badge variant="secondary">{meeting.status === "encerrada" ? "Encerrada" : meeting.status === "em_andamento" ? "Ao vivo" : "Agendada"}</Badge></div><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{meeting.descricao || "Sala aberta para treinamento da equipe."}</p>{meeting.agendada_para && <p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="size-3.5" /> {new Date(meeting.agendada_para).toLocaleString("pt-BR")}</p>}</div><Link to={`/centro-treinamento/sala-reuniao/${meeting.id}`}><Button>Entrar <ChevronRight className="size-4" /></Button></Link></CardContent></Card>)}</div>}</div></Layout>;
}
