import React, { useMemo, useState } from "react";
import { CalendarDays, ChevronDown, Search, WalletCards } from "lucide-react";
import { formatBRL } from "@/lib/format";
import { classify, clienteDividaLabel, dateOf, fornecedorStatus, paidByShareForClient, valueOf } from "@/utils/financeiroRules";
import { useClienteFinanceiro } from "@/hooks/useClienteFinanceiro";

export default function ClienteSituacao({ clientes, movimentacoes }: { clientes: any[]; movimentacoes:any[] }) {
  const [clienteId,setClienteId]=useState<string>("");
  const [mes,setMes]=useState("");
  const [busca,setBusca]=useState("");
  const { movimentos, mensal, resumo } = useClienteFinanceiro(movimentacoes, clienteId || null);
  const cliente = clientes.find(c=>c.id===clienteId);
  const lista = useMemo(()=>movimentos.filter(m=>!mes || String(dateOf(m)||"").slice(0,7)===mes).filter(m=>!busca || `${m.descricao||""} ${m.fornecedor_nome||""} ${m.numero_doc||""}`.toLowerCase().includes(busca.toLowerCase())),[movimentos,mes,busca]);
  const meses = useMemo(()=>Array.from(new Set(mensal.map(m=>m.periodo))).sort().reverse(),[mensal]);

  if (!clienteId) return <div className="rounded-2xl border border-dashed border-border bg-card/40 p-10 text-center"><WalletCards className="mx-auto h-10 w-10 text-primary/60"/><h3 className="mt-3 text-lg font-bold">Situação do Cliente</h3><p className="mt-1 text-sm text-muted-foreground">Selecione um cliente para abrir a conta corrente financeira.</p><div className="mx-auto mt-5 max-w-md"><select value={clienteId} onChange={e=>setClienteId(e.target.value)} className="w-full rounded-xl border border-border bg-background px-4 py-3 text-sm"><option value="">Selecione um cliente...</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></div></div>;

  return <div className="space-y-5">
    <div className="flex flex-col lg:flex-row lg:items-center gap-3"><div className="flex-1"><div className="text-xs uppercase tracking-wider text-muted-foreground">Cliente selecionado</div><div className="text-xl font-bold">{cliente?.nome}</div></div><div className="flex gap-2"><select value={clienteId} onChange={e=>setClienteId(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"><option value="">Trocar cliente</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select><select value={mes} onChange={e=>setMes(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"><option value="">Todos os meses</option>{meses.map(m=><option key={m} value={m}>{m}</option>)}</select></div></div>
    <div className="grid grid-cols-2 xl:grid-cols-5 gap-3">
      <Kpi label="Despesas" value={resumo.despesas} tone="text-foreground" />
      <Kpi label="Share antecipou" value={resumo.sharePagou} tone="text-amber-400" />
      <Kpi label="Cliente pagou direto" value={resumo.clientePagouDireto} tone="text-blue-400" />
      <Kpi label="Cliente pagou Share" value={resumo.recebidoShare} tone="text-emerald-400" />
      <Kpi label="Em aberto" value={resumo.aberto} tone="text-red-400" />
    </div>
    <div className="rounded-2xl border border-border bg-card/60 overflow-hidden">
      <div className="border-b border-border p-4"><div className="font-bold">Evolução mensal</div><div className="text-xs text-muted-foreground">A dívida acumulada considera apenas despesas do cliente pagas antecipadamente pela Share.</div></div>
      <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-muted/30 text-[10px] uppercase tracking-wider text-muted-foreground"><th className="text-left px-4 py-3">Mês</th><th className="text-right px-4 py-3">Despesas</th><th className="text-right px-4 py-3">Share pagou</th><th className="text-right px-4 py-3">Direto</th><th className="text-right px-4 py-3">Recebido</th><th className="text-right px-4 py-3">Aberto</th></tr></thead><tbody>{mensal.map(r=><tr key={r.periodo} className="border-t border-border/60"><td className="px-4 py-3 font-semibold">{r.periodo}</td><td className="px-4 py-3 text-right">{formatBRL(r.despesas)}</td><td className="px-4 py-3 text-right text-amber-400">{formatBRL(r.sharePagou)}</td><td className="px-4 py-3 text-right text-blue-400">{formatBRL(r.clientePagouDireto)}</td><td className="px-4 py-3 text-right text-emerald-400">{formatBRL(r.recebidoShare)}</td><td className="px-4 py-3 text-right font-bold text-red-400">{formatBRL(r.aberto)}</td></tr>)}</tbody></table></div>
    </div>
    <div className="rounded-2xl border border-border bg-card/60 overflow-hidden"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3 p-4 border-b border-border"><div className="font-bold">Extrato do cliente</div><div className="relative"><Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar despesa..." className="rounded-lg border border-border bg-background pl-8 pr-3 py-2 text-sm"/></div></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="bg-muted/30 text-[10px] uppercase tracking-wider text-muted-foreground"><th className="text-left px-4 py-3">Data</th><th className="text-left px-4 py-3">Descrição</th><th className="text-left px-4 py-3">Fornecedor</th><th className="text-right px-4 py-3">Valor</th><th className="text-left px-4 py-3">Fluxo do cliente</th><th className="text-left px-4 py-3">Fornecedor</th></tr></thead><tbody>{lista.map(m=>{const natureza=classify(m).natureza;return <tr key={m.id} className="border-t border-border/60 hover:bg-muted/20"><td className="px-4 py-3 whitespace-nowrap">{dateOf(m) ? new Date(dateOf(m)+"T00:00:00").toLocaleDateString("pt-BR") : "—"}</td><td className="px-4 py-3 font-medium">{m.descricao||"—"}</td><td className="px-4 py-3">{m.fornecedor_nome||"—"}</td><td className="px-4 py-3 text-right font-bold">{formatBRL(valueOf(m))}</td><td className="px-4 py-3"><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-semibold ${paidByShareForClient(m)?"bg-amber-500/10 text-amber-400":"bg-blue-500/10 text-blue-400"}`}>{clienteDividaLabel(m)}</span></td><td className="px-4 py-3"><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-semibold ${fornecedorStatus(m)==="pago"?"bg-emerald-500/10 text-emerald-400":"bg-red-500/10 text-red-400"}`}>{fornecedorStatus(m)}</span></td></tr>})}</tbody></table></div>{lista.length===0&&<div className="p-8 text-center text-sm text-muted-foreground">Nenhum lançamento encontrado.</div>}</div>
  </div>;
}
function Kpi({label,value,tone}:{label:string;value:number;tone:string}){return <div className="rounded-xl border border-border bg-card/60 p-3"><div className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</div><div className={`mt-1 text-lg font-bold ${tone}`}>{formatBRL(value)}</div></div>}
