import React, { useMemo } from "react";
import { Building2, HandCoins, Landmark, Users } from "lucide-react";
import { formatBRL } from "@/lib/format";
import { dateOf, dgaPayerLabel, isDga, isDgaCotistaOutOfPocket, isDgaPaidByBank, isEntrada, periodOf, valueOf } from "@/utils/financeiroRules";

export default function DgaSituacao({ movimentacoes, socios }: { movimentacoes:any[]; socios:any[] }) {
  const dga = movimentacoes.filter(isDga).filter(m=>String(m.status||'').toLowerCase()!=="cancelado");
  const entradas = dga.filter(isEntrada).reduce((s,m)=>s+valueOf(m),0);
  const saidasBanco = dga.filter(isDgaPaidByBank).reduce((s,m)=>s+valueOf(m),0);
  const saidasCotistas = dga.filter(isDgaCotistaOutOfPocket).reduce((s,m)=>s+valueOf(m),0);
  const saldo = entradas - saidasBanco;
  const cotistaMap = new Map<string,number>();
  dga.filter(isDgaCotistaOutOfPocket).forEach(m=>{const key=m.socio_id||m.socios_nome||"Cotista não identificado";cotistaMap.set(key,(cotistaMap.get(key)||0)+valueOf(m))});
  const cotistas = Array.from(cotistaMap.entries()).map(([id,total])=>({id,total,nome:socios.find(s=>s.id===id)?.nome||id})).sort((a,b)=>b.total-a.total);
  const mensal = useMemo(()=>{const map=new Map<string,any>();for(const m of dga){const p=periodOf(dateOf(m));if(!p)continue;if(!map.has(p))map.set(p,{periodo:p,aportes:0,despesasBanco:0,pagoCotistas:0});const r=map.get(p);if(isEntrada(m))r.aportes+=valueOf(m);else if(isDgaCotistaOutOfPocket(m))r.pagoCotistas+=valueOf(m);else r.despesasBanco+=valueOf(m);}return Array.from(map.values()).sort((a,b)=>a.periodo.localeCompare(b.periodo))},[dga]);
  return <div className="space-y-5"><div className="rounded-2xl border border-violet-500/20 bg-violet-500/[0.04] p-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-violet-500/10 p-3"><Building2 className="h-5 w-5 text-violet-400"/></div><div><div className="text-xs uppercase tracking-wider text-violet-300/70">Entidade independente</div><h2 className="text-xl font-bold">DGA </h2><p className="mt-1 text-sm text-muted-foreground">Despesas pagas pelo banco da DGA não geram dívida com a Share. Quando um cotista paga do próprio bolso, o saldo fica para acerto no balanço da DGA.</p></div></div></div>
  <div className="grid grid-cols-2 xl:grid-cols-5 gap-3"><Kpi label="Saldo bancário" value={saldo} icon={Landmark}/><Kpi label="Aportes" value={entradas} icon={Landmark}/><Kpi label="Despesas banco DGA" value={saidasBanco} icon={Building2}/><Kpi label="Pago por cotistas" value={saidasCotistas} icon={Users}/><Kpi label="A acertar com cotistas" value={saidasCotistas} icon={HandCoins}/></div>
  <div className="rounded-2xl border border-border bg-card/60 overflow-hidden"><div className="p-4 border-b border-border"><div className="font-bold">Movimentação mensal da DGA</div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-muted/30 text-[10px] uppercase tracking-wider text-muted-foreground"><th className="text-left px-4 py-3">Mês</th><th className="text-right px-4 py-3">Aportes</th><th className="text-right px-4 py-3">Despesas banco</th><th className="text-right px-4 py-3">Pago cotistas</th></tr></thead><tbody>{mensal.map(r=><tr key={r.periodo} className="border-t border-border/60"><td className="px-4 py-3 font-semibold">{r.periodo}</td><td className="px-4 py-3 text-right text-emerald-400">{formatBRL(r.aportes)}</td><td className="px-4 py-3 text-right text-red-400">{formatBRL(r.despesasBanco)}</td><td className="px-4 py-3 text-right text-amber-400">{formatBRL(r.pagoCotistas)}</td></tr>)}</tbody></table></div></div>
  <div className="rounded-2xl border border-border bg-card/60 overflow-hidden"><div className="p-4 border-b border-border flex items-center gap-2"><Users className="h-4 w-4 text-violet-400"/><div className="font-bold">Acertos pendentes com cotistas</div></div><div className="divide-y divide-border/60">{cotistas.length===0?<div className="p-8 text-center text-sm text-muted-foreground">Nenhum pagamento pessoal de cotista identificado.</div>:cotistas.map(c=><div key={c.id} className="flex items-center justify-between px-4 py-3"><div><div className="font-semibold">{c.nome}</div><div className="text-xs text-muted-foreground">Pago diretamente pelo cotista</div></div><div className="text-lg font-bold text-amber-400">{formatBRL(c.total)}</div></div>)}</div></div>
  </div>;
}
function Kpi({label,value,icon:Icon}:{label:string;value:number;icon:any}){return <div className="rounded-xl border border-border bg-card/60 p-3"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</span><Icon className="h-4 w-4 text-violet-400"/></div><div className="mt-1 text-lg font-bold">{formatBRL(value)}</div></div>}
